name:          义乌购前端代码规范
description:   开发灵活，稳定，可持续 HTML 和 CSS 代码的规范
url:           http://www.zhujiangwei.com/FeCodeGuide

include:       [".editorconfig", ".jscsrc", ".jshintrc", ".csslintrc", ".scss-lint.yml"]
highlighter:   rouge
markdown:      rdiscount
permalink:     pretty
