name:          义乌购前端编码规范
description:   Standards for developing flexible, durable, and sustainable HTML and CSS, and maintainable JavaScript
url:           http://www.zhujiangwei.com/FeCodeGuide

include:       [".editorconfig", ".jscsrc", ".jshintrc", ".csslintrc", ".scss-lint.yml"]

markdown:      rdiscount
permalink:     pretty
pygments:      true
